version: 0.2

env:
  secrets-manager:
    SEMGREP_APP_TOKEN: "semgrep_token:SEMGREP_APP_TOKEN"
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip3 install semgrep
  # pre_build:
  #   commands:
  #     - echo Test
  build:
    commands:
      
      - semgrep ci
