version: 0.2

env:
  exported-variables:
    - $SEMGREP_APP_TOKEN
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install semgrep
  pre_build:
    commands:
      - echo Test
  build:
    commands:
      
      - semgrep ci
