version: 0.2

env:
  exported-variables:
    - $SEMGREP_APP_TOKEN
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Test
  build:
    commands:
      - sh pip3 install semgrep
      - sh semgrep ci
