---
- name: A playbook Weave Socks
  hosts: laravelserver
  become: yes
  tasks:
    - name: "Update Repository cache"
      apt:
        update_cache: true
        cache_valid_time: 3600
    
    - name: Install Java for jenkins
      apt:
        name: openjdk-11-jre-headless
        state: latest

    - name: Download jenkins apt_key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Download jenkins Repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Update apt repo 
      apt:
        update_cache: true
        state: latest

    - name: Jenkins installation
      apt:
        name: jenkins
        state: present
    
    - name: Start jenkins
      service:
        name: jenkins
        enabled: true
        state: started

    - name: Add jenkins user to sudoers
      user:
        name: jenkins
        group: sudo
        append: yes

    - name: Install dependencies needed for docker
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - unzip

    - name: add GPG key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install aws cli
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Configure AWS.
      shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
      no_log: True
      with_dict:
        aws_access_key_id: "{{ aws_access_key_id }}"
        aws_secret_access_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        format: "{{ aws_format }}"
      changed_when: false
